### PR TITLE
Chintai Tokenomic Model (한국어)

### PR DESCRIPTION
**Pull request by seankook**
[Chintai Tokenomic Model (한국어).pdf](https://github.com/chintai-platform/whitepapers/files/3054186/Chintai.Tokenomic.Model.pdf)

### CODE REVIEW

**Comment by acoutts** [comment]
2 fixes before we can merge:
- Update version # to 1.3 to match English copy
- Update the distribution section on page 5 to reflect 320 rounds and 1,875,000 tokens number now.

**Comment by seankook** [comment]
[Chintai Tokenomic Model (한국어).pdf](https://github.com/chintai-platform/whitepapers/files/3054178/Chintai.Tokenomic.Model.pdf)

**Comment by seankook** [comment]
done.

**Comment by acoutts** [comment]
> [Chintai Tokenomic Model (한국어).pdf](https://github.com/chintai-platform/whitepapers/files/3054178/Chintai.Tokenomic.Model.pdf)

I dont think this got committed to this PR and is just living as an attachment here

**Pull request closed without merging**
